// flag_DW                        0
// out_mult                       20
// out_mult2                      0
// out_shift                      23
// FLAG_BATCHNORM                 1
// FLAG_RELU                      1
// weight_T                       0
// to_compute_acc_in              0
// to_compute_acc_out             0
// test_location                  L3
// tile_dim_h                     1
// tile_dim_w                     2
// optional                       conv
// conv_order                     PULP-NN
// type                           char
// func_name                      layerConvBNRelu7
// l1_x_offset                    0
// l1_y_offset                    6148
// l1_W_offset                    6408
// l1_k_offset                    24852
// l1_lambda_offset               25112
// k_size_byte                    256
// lambda_size_byte               512
// k_tile_size_byte               16
// lambda_tile_size_byte          32
// tile_dim_nof                   16
// tile_dim_nif                   1
// border                         1
// nof                            128
// nif                            128
// h                              4
// w                              7
// fs1                            3
// fs2                            3
// conv_overlap1                  2
// conv_overlap2                  2
// has_bias                       0
// padding                        1
// stride                         1
// x_h                            4
// x_w                            7
// x_data_size_byte               1
// x_tile_size_nif                128
// x_tile_size_h                  4
// x_tile_size_w                  6
// x_tile_size_byte               3072
// x_stride_w_byte                896
// x_stride_c_byte                128
// x_length_nif_px                128
// x_length_nif_byte              128
// x_length_h_px                  4
// x_length_w_byte                6
// x_tile_size_nif_last           128
// x_tile_size_h_last             4
// x_tile_size_w_last             4
// x_length_nif_px_last           128
// x_length_nif_byte_last         128
// x_length_h_px_last             4
// x_length_w_byte_last           4
// x_tile_size_byte_first         3072
// x_length_nif_px_first          128
// x_length_nif_byte_first        128
// x_length_h_px_first            4
// x_length_w_byte_first          6
// W_nof                          128
// b_tile_size_byte               8
// W_nif                          128
// W_data_size_byte               1
// W_tile_size_nof                8
// W_tile_size_nif                128
// W_tile_size_byte               9216
// W_stride_nof_byte              1152
// W_stride_hw_byte               128
// W_length_nif_byte              128
// W_tile_size_nof_last           8
// W_tile_size_nif_last           128
// W_length_nif_byte_last         128
// W_tile_size_byte_first         9216
// W_length_nif_byte_first        128
// b_size_byte                    128
// l2_off_k                       147456
// l2_off_lambda                  147712
// y_h                            4
// y_w                            7
// y_data_size_byte               1
// y_tile_size_nof                8
// y_tile_size_h                  4
// y_tile_size_w                  4
// y_tile_size_byte               128
// y_stride_w_byte                896
// y_stride_c_byte                128
// y_length_nof_px                8
// y_length_nof_byte              8
// y_length_h_px                  4
// y_length_w_byte                4
// y_tile_size_nof_last           8
// y_tile_size_h_last             4
// y_tile_size_w_last             3
// y_length_nof_px_last           8
// y_length_w_byte_last           3
// y_length_nof_byte_last         8


#include "pulp.h"
#include "dory.h"
#include "stats.h"

void  layerConvBNRelu7(
  unsigned int l2_x,
  unsigned int l2_y,
  unsigned int l2_W,
  unsigned int l1_buffer,
  unsigned int out_mult_in,
  unsigned int out_shift_in
);
