// flag_DW                        0
// out_mult                       30
// out_mult2                      0
// out_shift                      23
// FLAG_BATCHNORM                 1
// FLAG_RELU                      1
// weight_T                       0
// to_compute_acc_in              0
// to_compute_acc_out             0
// test_location                  L3
// tile_dim_h                     8
// tile_dim_w                     14
// optional                       conv
// conv_order                     PULP-NN
// type                           char
// func_name                      layerConvBNRelu4
// l1_x_offset                    0
// l1_y_offset                    580
// l1_W_offset                    704
// l1_k_offset                    35276
// l1_lambda_offset               35408
// k_size_byte                    128
// lambda_size_byte               256
// k_tile_size_byte               120
// lambda_tile_size_byte          240
// tile_dim_nof                   2
// tile_dim_nif                   1
// border                         1
// nof                            64
// nif                            32
// h                              16
// w                              28
// fs1                            3
// fs2                            3
// conv_overlap1                  1
// conv_overlap2                  1
// has_bias                       0
// padding                        1
// stride                         2
// x_h                            16
// x_w                            28
// x_data_size_byte               1
// x_tile_size_nif                32
// x_tile_size_h                  3
// x_tile_size_w                  3
// x_tile_size_byte               288
// x_stride_w_byte                896
// x_stride_c_byte                32
// x_length_nif_px                32
// x_length_nif_byte              32
// x_length_h_px                  3
// x_length_w_byte                3
// x_tile_size_nif_last           32
// x_tile_size_h_last             3
// x_tile_size_w_last             3
// x_length_nif_px_last           32
// x_length_nif_byte_last         32
// x_length_h_px_last             3
// x_length_w_byte_last           3
// x_tile_size_byte_first         288
// x_length_nif_px_first          32
// x_length_nif_byte_first        32
// x_length_h_px_first            3
// x_length_w_byte_first          3
// W_nof                          64
// b_tile_size_byte               60
// W_nif                          32
// W_data_size_byte               1
// W_tile_size_nof                60
// W_tile_size_nif                32
// W_tile_size_byte               17280
// W_stride_nof_byte              288
// W_stride_hw_byte               32
// W_length_nif_byte              32
// W_tile_size_nof_last           4
// W_tile_size_nif_last           32
// W_length_nif_byte_last         32
// W_tile_size_byte_first         17280
// W_length_nif_byte_first        32
// b_size_byte                    64
// l2_off_k                       18432
// l2_off_lambda                  18560
// y_h                            8
// y_w                            14
// y_data_size_byte               1
// y_tile_size_nof                60
// y_tile_size_h                  1
// y_tile_size_w                  1
// y_tile_size_byte               60
// y_stride_w_byte                896
// y_stride_c_byte                64
// y_length_nof_px                60
// y_length_nof_byte              60
// y_length_h_px                  1
// y_length_w_byte                1
// y_tile_size_nof_last           4
// y_tile_size_h_last             1
// y_tile_size_w_last             1
// y_length_nof_px_last           4
// y_length_w_byte_last           1
// y_length_nof_byte_last         4


#include "pulp.h"
#include "dory.h"
#include "stats.h"

void  layerConvBNRelu4(
  unsigned int l2_x,
  unsigned int l2_y,
  unsigned int l2_W,
  unsigned int l1_buffer,
  unsigned int out_mult_in,
  unsigned int out_shift_in
);
